// Isolated PostgreSQL (PGlite), never connects to Supabase or reads .env.
// Runtime supplied externally so production dependencies remain unchanged.
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { createRequire } from "node:module";
const runtime = process.env.BALANCE_TEST_RUNTIME;
if (!runtime) throw new Error("Set BALANCE_TEST_RUNTIME to the package.json of a temporary installation of @electric-sql/pglite.");
const { PGlite } = createRequire(runtime)("@electric-sql/pglite");
process.on("uncaughtException", (error) => { console.error(error.message, error.where ?? "", error.query ?? ""); process.exit(1); });
const db = new PGlite();
const query = async (sql, args = []) => (await db.query(sql, args)).rows;
const scalar = async (sql, args = []) => Object.values((await query(sql, args))[0])[0];
await db.exec(`
  CREATE ROLE anon; CREATE ROLE authenticated; CREATE SCHEMA auth;
  CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS
    $$ SELECT nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
  CREATE TABLE public.transactions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(), date date, description text,
    tx_id text, amount numeric, in_totals boolean, account_id text, balance numeric);
  CREATE TABLE public.tags (id bigint PRIMARY KEY, name text NOT NULL UNIQUE,
    color text, created_at timestamptz NOT NULL DEFAULT now());
  CREATE TABLE public.transaction_tags (
    transaction_id bigint NOT NULL REFERENCES public.transactions(id) ON DELETE CASCADE,
    tag_id bigint NOT NULL REFERENCES public.tags(id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(transaction_id, tag_id));
  CREATE TABLE public.account_balance_checkpoints (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, account_id text NOT NULL,
    as_of_date date NOT NULL, amount numeric NOT NULL, created_at timestamptz NOT NULL DEFAULT now(),
    checkpoint_type text NOT NULL CHECK(checkpoint_type IN ('certified','derived')),
    CHECK(amount::text NOT IN ('NaN','Infinity','-Infinity')), UNIQUE(account_id,as_of_date));
  INSERT INTO public.tags(id,name) VALUES(1,'Fixture');
  INSERT INTO public.account_balance_checkpoints(account_id,as_of_date,amount,checkpoint_type)
    VALUES('FINECO_MAIN', (date_trunc('month',now() AT TIME ZONE 'Europe/Rome') - interval '9 months' - interval '1 day')::date,23536.74,'certified');
  WITH values_by_month AS (
    SELECT i, amount, lag(amount,1,23536.74::numeric) OVER(ORDER BY i) AS previous
    FROM unnest(ARRAY[27131.88,22734.68,25813.26,50666.06,76667.91,62039.94,62536.31,60674.56,40337.02]::numeric[])
      WITH ORDINALITY AS v(amount,i)
  )
  INSERT INTO public.transactions(tx_id,date,description,amount,account_id,in_totals,balance)
    SELECT 'month-'||i, (date_trunc('month',now() AT TIME ZONE 'Europe/Rome') + (i-10)*interval '1 month' + interval '1 day')::date,
      'Monthly fixture', amount-previous,'FINECO_MAIN',true,amount FROM values_by_month;
  INSERT INTO public.account_balance_checkpoints(account_id,as_of_date,amount,checkpoint_type)
    SELECT 'FINECO_MAIN',(date_trunc('month',date::timestamp)+interval '1 month'-interval '1 day')::date,balance,'derived'
    FROM public.transactions;
  INSERT INTO public.transactions(tx_id,date,description,amount,account_id,in_totals,balance)
    VALUES('current-1', (now() AT TIME ZONE 'Europe/Rome')::date,'Current fixture',-10,'FINECO_MAIN',true,40327.02),
      ('current-2',(now() AT TIME ZONE 'Europe/Rome')::date,'Current fixture',0.61,'FINECO_MAIN',true,40327.63);
  INSERT INTO public.transactions(tx_id,date,description,amount,account_id,in_totals,balance)
    SELECT 'zero-'||i,date,'Ordering fixture',0,'FINECO_MAIN',true,27131.88
    FROM generate_series(1,112) i CROSS JOIN (SELECT date FROM public.transactions WHERE tx_id='month-1') d;
  SELECT set_config('request.jwt.claim.sub','11111111-1111-1111-1111-111111111111',false);
`);
const state = () => scalar(`SELECT jsonb_build_object(
  'transactions',(SELECT jsonb_agg(to_jsonb(t) ORDER BY id) FROM transactions t),
  'checkpoints',(SELECT jsonb_agg(to_jsonb(c) ORDER BY id) FROM account_balance_checkpoints c),
  'tags',(SELECT jsonb_agg(to_jsonb(a) ORDER BY transaction_id,tag_id) FROM transaction_tags a))`);
const financialState = () => scalar(`SELECT jsonb_build_object(
  'balances',(SELECT jsonb_agg(jsonb_build_array(id,balance) ORDER BY id) FROM transactions),
  'checkpoints',(SELECT jsonb_agg(to_jsonb(c) ORDER BY id) FROM account_balance_checkpoints c))`);
const beforeInstall = await state();
await db.exec(readFileSync(new URL('../supabase/migrations/20261002160000_balance_engine.sql',import.meta.url),'utf8'));
assert.deepEqual(await state(), beforeInstall, 'Installation must not mutate financial data');
const save = (id, field = '', value = null, tags = null) => scalar(`SELECT save_transaction(
  'update',tx_id,${field==='date'?'$1::date':'date'},${field==='description'?'$1::text':'description'},
  ${field==='amount'?'$1::numeric':'amount'},${field==='account_id'?'$1::text':'account_id'},
  ${field==='in_totals'?'$1::boolean':'in_totals'},$2::jsonb)
  FROM transactions WHERE tx_id=$3 AND ${field ? "true" : "$1::text IS NULL"}`, [value, tags, id]);
async function check(name, fn) {
  await db.exec('BEGIN');
  try { await fn(); console.log('PASS',name); }
  finally { await db.exec('ROLLBACK'); }
}
async function fails(sql,args=[]) {
  await db.exec('SAVEPOINT expected_failure');
  let failed=false;
  try { await query(sql,args); } catch { failed=true; }
  await db.exec('ROLLBACK TO SAVEPOINT expected_failure; RELEASE SAVEPOINT expected_failure');
  assert.equal(failed,true,'Expected exception');
}
const reconcile = async () => {
  assert.equal(await scalar(`WITH e AS (SELECT t.id,t.balance,c.amount+sum(t.amount) OVER(
    ORDER BY t.date,t.created_at,t.id ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS expected
    FROM transactions t JOIN account_balance_checkpoints c ON c.account_id=t.account_id AND c.checkpoint_type='certified'
    WHERE t.account_id='FINECO_MAIN' AND t.date>c.as_of_date)
    SELECT count(*)::int FROM e WHERE balance IS DISTINCT FROM expected`),0);
  assert.equal(await scalar(`SELECT _balance_first_invalid_month('FINECO_MAIN')`),null);
};
await check('baseline: 123 movements, 10 checkpoints, exact 40327.63',async()=>{
  assert.equal(await scalar('SELECT count(*)::int FROM transactions'),123);
  assert.equal(await scalar('SELECT count(*)::int FROM account_balance_checkpoints'),10);
  assert.equal(String(await scalar("SELECT get_account_balance('FINECO_MAIN')")),'40327.63');
  await reconcile();
});
for (const [name,field,value,tags] of [
  ['no change','',null,null],['description','description','New metadata',null],
  ['in_totals','in_totals',false,null],['tags','',null,'["1"]'],
]) await check(`${name}: no financial writes/rebuild`,async()=>{
  const before=await financialState(); const result=await save('month-1',field,value,tags);
  assert.equal(result.financial_changed,false); assert.deepEqual(result.rebuilds,[]);
  assert.deepEqual(await financialState(),before);
});
for(const [name,id,index] of [['current','current-1',0],['previous','month-9',1],['retroactive','month-7',3]]) {
  await check(`${name} amount rebuild uses preceding valid checkpoint`,async()=>{
    const original=Number(await scalar('SELECT amount FROM transactions WHERE tx_id=$1',[id]));
    const result=await save(id,'amount',original+1);
    const base=await scalar(`SELECT (date_trunc('month',now() AT TIME ZONE 'Europe/Rome') - $1::int*interval '1 month' - interval '1 day')::date::text`,[index]);
    assert.equal(result.rebuilds[0].base_date,base); await reconcile();
  });
}
for(const [id,target] of [['month-9',7],['month-7',9]]) await check('date move '+id,async()=>{
  const date=await scalar('SELECT date::text FROM transactions WHERE tx_id=$1',['month-'+target]);
  const result=await save(id,'date',date);
  assert.equal(result.financial_changed,true); await reconcile();
});
await check('missing cache expands rebuild to earliest gap',async()=>{
  const missing=await scalar("DELETE FROM account_balance_checkpoints WHERE as_of_date=(SELECT (date_trunc('month',date::timestamp)+interval '1 month'-interval '1 day')::date FROM transactions WHERE tx_id='month-3') RETURNING (date_trunc('month',as_of_date::timestamp))::date::text");
  const result=await save('current-1','amount',-9);
  assert.equal(result.rebuilds[0].effective_month,missing); await reconcile();
});
await check('corrupted cache repaired; get balance never trusts it',async()=>{
  await db.exec("UPDATE account_balance_checkpoints SET amount=amount+100 WHERE as_of_date=(SELECT (date_trunc('month',date::timestamp)+interval '1 month'-interval '1 day')::date FROM transactions WHERE tx_id='month-6')");
  assert.equal(String(await scalar("SELECT get_account_balance('FINECO_MAIN')")),'40327.63');
  const result=await scalar("SELECT ensure_balance_checkpoints('FINECO_MAIN')");
  assert.equal(result.rebuilt,true); await reconcile();
});
await check('certified UPDATE/DELETE/promotion rejected; derived DELETE allowed',async()=>{
  await fails("UPDATE account_balance_checkpoints SET amount=amount+1 WHERE checkpoint_type='certified'");
  await fails("DELETE FROM account_balance_checkpoints WHERE checkpoint_type='certified'");
  await fails("UPDATE account_balance_checkpoints SET checkpoint_type='certified' WHERE checkpoint_type='derived'");
  const before=await scalar('SELECT count(*)::int FROM account_balance_checkpoints');
  await db.exec("DELETE FROM account_balance_checkpoints WHERE checkpoint_type='derived'");
  assert.equal(await scalar('SELECT count(*)::int FROM account_balance_checkpoints'),before-9);
  await scalar("SELECT ensure_balance_checkpoints('FINECO_MAIN')"); await reconcile();
});
await check('invalid tags and missing base roll back entire save',async()=>{
  const before=await state();
  await fails(`SELECT save_transaction('update',tx_id,date,description,amount+1,account_id,in_totals,'[999]'::jsonb) FROM transactions WHERE tx_id='current-1'`);
  assert.deepEqual(await state(),before);
  await fails(`SELECT save_transaction('update',tx_id,date,description,amount,'NO_BASE',in_totals,'[1]'::jsonb) FROM transactions WHERE tx_id='current-1'`);
  assert.deepEqual(await state(),before);
});
await check('retroactive INSERT then DELETE; stable order with identical timestamp',async()=>{
  const date=await scalar("SELECT date::text FROM transactions WHERE tx_id='month-7'");
  const r=await scalar(`SELECT save_transaction('insert','new-fixture',$1::date,'Inserted',2,'FINECO_MAIN',true,'[1]'::jsonb)`,[date]);
  assert.notEqual(r.transaction.balance,null); await reconcile();
  await scalar("SELECT delete_transaction('new-fixture')"); await reconcile();
  assert.equal(await scalar('SELECT count(*)::int FROM transactions'),123);
});
await check('account move rebuilds both accounts atomically',async()=>{
  await db.exec("INSERT INTO account_balance_checkpoints(account_id,as_of_date,amount,checkpoint_type) SELECT 'SECOND',as_of_date,100,'certified' FROM account_balance_checkpoints WHERE checkpoint_type='certified'");
  const result=await save('month-7','account_id','SECOND','[1]');
  assert.equal(result.rebuilds.length,2); await reconcile();
  assert.equal(await scalar("SELECT _balance_first_invalid_month('SECOND')"),null);
});
await check('financial mutation at certified boundary rejected',async()=>{
  const date=await scalar("SELECT as_of_date::text FROM account_balance_checkpoints WHERE checkpoint_type='certified'");
  await fails(`SELECT save_transaction('insert','bad-date',$1::date,'Bad',1,'FINECO_MAIN',true,NULL)`,[date]);
});
await check('thousands of rows, empty months and year boundary',async()=>{
  await db.exec(`DELETE FROM transactions WHERE tx_id='month-4';
    INSERT INTO transactions(tx_id,date,description,amount,account_id,in_totals,balance)
    SELECT 'bulk-'||i,date,'Bulk',0.01,'FINECO_MAIN',true,NULL
    FROM generate_series(1,2000) i CROSS JOIN (SELECT date FROM transactions WHERE tx_id='month-1') d;`);
  await scalar("SELECT ensure_balance_checkpoints('FINECO_MAIN')"); await reconcile();
  assert.equal(await scalar('SELECT count(*)::int FROM transactions WHERE balance IS NULL'),0);
  assert.equal(await scalar("SELECT count(*)::int FROM account_balance_checkpoints WHERE as_of_date>=date_trunc('month',now() AT TIME ZONE 'Europe/Rome')::date"),0);
});
await check('exception during rebuild rolls back movement, tags and preceding updates',async()=>{
  const before=await state();
  await db.exec(`CREATE FUNCTION pg_temp.fail_rebuild() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN IF NEW.tx_id='current-2' AND NEW.balance IS DISTINCT FROM OLD.balance THEN
      RAISE EXCEPTION 'Injected rebuild failure'; END IF; RETURN NEW; END; $$;
    CREATE TRIGGER fixture_failure BEFORE UPDATE ON transactions FOR EACH ROW EXECUTE FUNCTION pg_temp.fail_rebuild();`);
  await fails(`SELECT save_transaction('update',tx_id,date,description,amount+1,account_id,in_totals,'[1]'::jsonb)
    FROM transactions WHERE tx_id='current-1'`);
  assert.deepEqual(await state(),before);
});
await check('API permissions: public RPC allowed; helpers and anonymous access denied',async()=>{
  await db.exec('SET LOCAL ROLE authenticated');
  assert.equal(String(await scalar("SELECT get_account_balance('FINECO_MAIN')")),'40327.63');
  await fails("SELECT _balance_rebuild('FINECO_MAIN',CURRENT_DATE)");
  await db.exec('RESET ROLE; SET LOCAL ROLE anon');
  await fails("SELECT get_account_balance('FINECO_MAIN')");
  await db.exec('RESET ROLE');
});
console.log('All isolated database checks passed; this does not verify production Supabase.');
await db.close();
